import { DocumentAnalyzer } from '../../../analyzer/documentAnalyzer';
import { getDefinitions, getReferences } from '../../../analyzer/navigation';
import * as assert from 'assert';
import { useWorkspaceFixtures } from '../../support/workspace';

suite('General macro reparsing', () => {
  const fixtures = useWorkspaceFixtures();
  function check(text: string) {
    return fixtures.createWorkspaceIndex().analyzeDocument({uri:'file:///macros.axl',version:1,text});
  }
  for (const newline of ['\n', '\r\n']) {
    for (const prefix of ['', '  ', newline, newline + newline + '  ']) {
      test(`preserves source positions with leading whitespace ${JSON.stringify({newline, prefix})}`, () => {
        const text = prefix + ['#define DEBUG if(0)', '', '',
          'void main(){ int value; DEBUG { value = 1; } }', ''].join(newline);
        const analysis = check(text);
        const lines = text.split('\n');
        const mainLine = lines.findIndex(line => line.startsWith('void main'));
        assert.deepStrictEqual(analysis.diagnostics, []);
        assert.strictEqual(analysis.expandedMacroReferences?.length, 1);
        assert.deepStrictEqual(analysis.declarations.find(d => d.name === 'main')?.selectionRange,
          {start:{line:mainLine, character:5}, end:{line:mainLine, character:9}});
        for (const declaration of analysis.declarations) {
          const range = declaration.selectionRange;
          assert.strictEqual(lines[range.start.line].slice(range.start.character, range.end.character), declaration.name);
        }
        for (const reference of analysis.navigationReferences ?? []) {
          const range = reference.range;
          assert.strictEqual(lines[range.start.line].slice(range.start.character, range.end.character), reference.name);
        }
      });
    }
  }
  test('reparses conditional prefixes before member calls', () => {
    const a = check('#define DEBUG if(0)\nclass Date { int x; void Now(){} }; void f(Date dat){ DEBUG dat.Now(); }');
    assert.deepStrictEqual(a.diagnostics, []);
    assert.ok(!a.declarations.some(d => d.name === 'Now' && d.containerName === 'f'));
  });
  test('reparses prefixes even when the original tree has no syntax error', () => {
    const a = check('#define DEBUG if(0)\nvoid ping(){} void f(){ DEBUG ping(); }');
    assert.deepStrictEqual(a.diagnostics, []);
    assert.strictEqual(a.declarations.filter(d => d.name === 'ping').length, 1);
  });
  test('indexes declarations generated by object macros', () => {
    const a = check('#define DECL int value;\nDECL\nvoid f(){ value = 1; }');
    assert.deepStrictEqual(a.diagnostics, []);
    assert.ok(a.declarations.some(d => d.name === 'value'));
  });
  test('indexes declarations generated by function macros', () => {
    const a = check('#define DECL(name) int name;\nDECL(value)\nvoid f(){ value = 1; }');
    assert.deepStrictEqual(a.diagnostics, []);
    assert.ok(a.declarations.some(d => d.name === 'value'));
  });
  test('reports invalid syntax introduced by expansion at its invocation', () => {
    const a = check('#define BAD )\nvoid f(){ BAD; }');
    assert.ok(a.diagnostics.some(d => d.message === 'Syntax error.' && d.range.start.line === 1));
  });
  test('honors undef and redefinition at each use', () => {
    const a = check('#define DECL int first;\nDECL\n#undef DECL\n#define DECL int second;\nDECL\nvoid f(){ first=1; second=2; }');
    assert.deepStrictEqual(a.diagnostics, []);
    assert.ok(a.declarations.some(d => d.name === 'first'));
    assert.ok(a.declarations.some(d => d.name === 'second'));
  });
  test('expands aliases of function macros', () => {
    const a = check('#define DECL(name) int name;\n#define ALIAS DECL\nALIAS(value)\nvoid f(){ value=1; }');
    assert.deepStrictEqual(a.diagnostics, []);
    assert.ok(a.declarations.some(d => d.name === 'value'));
  });
  test('does not substitute inside numeric tokens, strings or comments', () => {
    const a = check('#define xFF )\n#define HEX 0xFF\n#define TOKEN )\nvoid f(){ int value=HEX; string s="TOKEN"; /* TOKEN */ }');
    assert.deepStrictEqual(a.diagnostics, []);
  });
  test('checks missing types introduced by a declaration macro', () => {
    const a = check('#define DECL MissingType value;\nDECL');
    assert.ok(a.diagnostics.some(d => d.message === "Unknown type 'MissingType'." && d.range.start.line === 1));
  });
  test('preserves distinct argument references for navigation and rename', () => {
    const text='#define SUM(x,y) ((x)+(y))\nvoid f(){ int a; int b; int c=SUM(a,b); }';
    const index=fixtures.createWorkspaceIndex();
    const analysis=index.analyzeDocument({uri:'file:///args.axl',version:1,text});
    const b=analysis.declarations.find(d=>d.name==='b')!;
    assert.deepStrictEqual(getDefinitions({analysis,workspaceIndex:index,position:{line:1,character:36}}), [{uri:analysis.uri,range:b.selectionRange}]);
    const a=analysis.declarations.find(d=>d.name==='a')!;
    const refs=getReferences({analysis,workspaceIndex:index,position:a.selectionRange.start,includeDeclaration:false});
    assert.ok(refs.some(r=>r.range.start.line===1 && r.range.start.character===34), JSON.stringify(refs));
  });
  test('keeps imported conditional symbols aligned after multiline expansion', () => {
    const text='#define TWO int a; \\\n int b;\nTWO\n#include "header.axh"\n#if FLAG\nint selected;\n#else\nint other;\n#endif';
    const analysis=new DocumentAnalyzer().analyzeDocument({uri:'file:///branches.axl',version:1,text,
      preprocessorSymbols:[{name:'FLAG',value:'1',sourceRange:{start:{line:3,character:0},end:{line:3,character:21}}}]});
    assert.ok(analysis.declarations.some(d=>d.name==='selected'));
    assert.ok(!analysis.declarations.some(d=>d.name==='other'));
  });
  test('preserves positions following a multiline expansion', () => {
    const a = check('#define DECL int a; \\\nint b;\nvoid f(){ DECL missing; }');
    const d = a.diagnostics.find(d => d.message === "Unknown identifier 'missing'.");
    assert.ok(d, JSON.stringify(a.diagnostics));
    assert.deepStrictEqual(d.range, {start:{line:2,character:15},end:{line:2,character:22}});
  });
});
